# -*- coding: utf-8 -*-
"""class3_printcommandfunctionalities_CipherSchools.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/githubtanush/week1-Python-CipherSchools/blob/main/class3_printcommandfunctionalities_CipherSchools.ipynb
"""

print("Tanush Arora")

print("1, 2, 3, 4, 5, 6, 1+5, 1+5i")

print("Hello")
print("World 1")

print("Hello", end=" ")
print("World 1")