# -*- coding: utf-8 -*-
"""class4_akinguserinputandtypeconversion_CipherSchools.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/githubtanush/week1-Python-CipherSchools/blob/main/class4_akinguserinputandtypeconversion_CipherSchools.ipynb
"""

#delimeter is on;y\n character
a=input()
print(a)

type(a)

a=15
str(a)

int("1245464")

float("123.46464")

a = 65
a = 'A'