# -*- coding: utf-8 -*-
"""class2_basics_of_python_primitive_data_types,_comments,_variable_CipherSchools.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/githubtanush/week1-Python-CipherSchools/blob/main/class2_basics_of_python_primitive_data_types%2C_comments%2C_variable_CipherSchools.ipynb
"""

a=1
print(a)

a=200
print(a)

type(a)

type(a)

a=225
print(id(a))

print(hex(id(a)))

b=278
print(id(b))

c=278
print(id(c))

a=1
print(a)

a=200
print(a)

type(a)

type(a)

a=225
print(id(a))

print(hex(id(a)))

b=278
print(id(b))

c=278
print(id(c))