# -*- coding: utf-8 -*-
"""class5_Operators&expressions_CipherSchools.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/githubtanush/week1-Python-CipherSchools/blob/main/class5_Operators%26expressions_CipherSchools.ipynb
"""

5+5

10-5

10/3

10//3

10 % 3

2 ** 3

2*3

"TA" + "123" + "KILLS"

"abc" * 6

"hello" "hello " "hello"

1 ==1

1 ==3

1<2

1>2

"ab" < "z"  #Lexiography

"a" < "A"

True and False

True or False

True or 1

1 and 0

1 and 5

True = 2 # we can't assign any value

type(True)

isinstance(True, int)

"" or 2.5

bool("")

bool((1, 2, 3))

"" and 0

112 and ""

#Short Curcuiting
#a or b = a (if a is truthy)
#a or b = b ( if a is falsy)
#a and b = b (if a is truthy)
#a and b = a (if a is falsy)

#Short Curcuiting
#true or b = true
#false or b = b
#true and b = b
#false and b = false